title: Bosch CS 5800/6800i & Buderus Logatherm WLW176/186
description: Allerhand Informationen zu Wärmepumpen von Bosch & Buderus
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
